Implemented simple Tax Calculator
pawkli95/invoicing-system-Pawel-Klimek pull request #10
Opened 2021-10-01 18:50 UTC by pawkli95

2021-10-02 09:31 UTC, katdunaj approved these changes

2021-10-02 15:03 UTC, radoslawdabrowski requested changes

2021-10-02 15:03 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/utils/FileService.java
> +            Files.createFile(Paths.get(fileName));
Actually, if we have problem with creating a file this service should not be initialized, so it is better to throw some implementation of RuntimeException (or even checked Exception) than try catch in constructor.

2021-10-03 09:20 UTC, radoslawdabrowski requested changes

2021-10-03 09:20 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/utils/FileService.java
> +            throw new RuntimeException();
"implementation of RuntimeException" :) create e.g. FileNotCreatedException that extends RuntimeException and throw it here

2021-10-03 10:14 UTC, katdunaj submitted a review, later dismissed

2021-10-03 13:13 UTC, michalflis reviewed
In TaxCalculatorServiceIntegrationTest.groovy and TaxCalculatorServiceUnitTest.groovy you are testing the same, is it necessary?

2021-10-03 17:07 UTC, pawkli95 commented
> 
> 
> In TaxCalculatorServiceIntegrationTest.groovy and TaxCalculatorServiceUnitTest.groovy you are testing the same method, is it necessary?

I think so, in the unit test I tested only the method by mocking the database, and in integrationTest database has real implementation to test the whole module

2021-10-04 14:51 UTC, michalflis approved these changes

2021-10-05 07:07 UTC, katdunaj approved these changes

2021-10-05 12:58 UTC, radoslawdabrowski approved these changes

2021-10-05 13:16 UTC, merged