Task4
pawkli95/invoicing-system-Pawel-Klimek pull request #5
Opened 2021-09-06 15:03 UTC by pawkli95

I merged task3 and task4 into one pull request

2021-09-06 15:25 UTC, radoslawdabrowski requested changes

2021-09-06 15:25 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/db/fileBased/FileBasedDatabase.java
> +package pl.futurecollars.invoicing.db.fileBased;
Packages should be lower case only

2021-09-07 15:23 UTC, michalflis approved these changes

2021-09-07 15:25 UTC, radoslawdabrowski approved these changes

2021-09-07 15:44 UTC, merged